import '../styles/globals.scss';
import type { AppProps } from 'next/app';
import { Provider } from 'react-redux';

import MainPage from '../components/layout/MainPage';
import store from '../redux/store';
import { Fragment } from 'react';
import Head from 'next/head';

function MyApp({ Component, pageProps }: AppProps) {
    return (
        <Fragment>
            <Head>
                <title>Lucky Wheel</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Provider store={store}>
                <MainPage>
                    <Component {...pageProps} />
                </MainPage>
            </Provider>
        </Fragment>
    );
}
export default MyApp;
