import '../styles/globals.scss';
import type { AppProps } from 'next/app';
import { Provider } from 'react-redux';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

import MainPage from '../components/layout/MainPage';
import store from '../redux/store';
import { Fragment } from 'react';
import Head from 'next/head';
import SplashScreen from '../components/protected/SplashScreen';

function MyApp({ Component, pageProps }: AppProps) {
    return (
        <Fragment>
            <ToastContainer
                position="top-center"
                autoClose={3000}
                hideProgressBar={false}
                newestOnTop={false}
                closeOnClick
                rtl={false}
                pauseOnFocusLoss
                draggable
                pauseOnHover
            />
            <Head>
                <title>mini game</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1, maximum-scale=1"
                ></meta>
            </Head>
            <Provider store={store}>
                <SplashScreen>
                    <MainPage>
                        <Component {...pageProps} />
                    </MainPage>
                </SplashScreen>
            </Provider>
        </Fragment>
    );
}
export default MyApp;
